#AUTHENTICATION
AUTH:
  TOKEN: "" ### ADD YOUR DISCORD KEY HERE!!! ###

#COMMANDS
DOCS:
  JOIN: "-> joins the user's voice channel"
  LEAVE: "-> leaves the current voice channel"
  PLAY:  "-> plays the given youtube video or the first item in the queue"
  PAUSE: "-> pause/unpause the current playing video"
  QUEUE: "-> queues up the given youtube video"
  CLEAR: "-> clears the queue"
  ORG: "-> ( ͡° ͜ʖ ͡°)"

#MESSAGES
MESSAGES:
  JOINING_VOICE: "Joining the {channel} channel ＼(^ω^＼)"
  LEAVING_VOICE: "Leaving the {channel} channel（ミ￣ー￣ミ)"
  PLAYING: "Playing... (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧ \n{track}"
  PAUSING: "Paused... (/ω＼)	"
  RESUMING: "Resuming... °˖✧◝(⁰▿⁰)◜✧˖°	"
  QUEUING: "Queuing... (>ω^) \n{track}"
  CLEARING: "Clearing the queue... ( ╯°□°)╯ ┻━━┻"
  ORG: "♡ σ(≧ε≦σ) ♡"

#ERRORS
ERRORS:
  USER_NOT_IN_VCHANNEL: "{user}-chan, baka! You're not in a voice channel! ( ╥ω╥ )"
  BOT_NOT_IN_VCHANNEL: "{user}-chan, baka! I'm not in a voice channel! ( ╥ω╥ )"
  PLAYING_INVALID_LINK: "{user}-chan, baka! I cannot play invalid youtube links! ( ╥ω╥ )"
  EMPTY_QUEUE: "{user}-chan, baka! You didn't give me a youtube linke and the queue is empty ( ╥ω╥ )"

#YOUTUBE DOWNLOADER OPTIONS
YD_DL_OPTS:
  format: bestaudio/best
  postprocessors:
    - key: "FFmpegExtractAudio"
      preferredcodec: "mp3"
      preferredquality: "192"
  "retries": 3
  "restrict-filenames": True
  "no-playlist": True
  'quiet': False
